spring:
  application:
    name: micro-MoneyExchange
  data:
    redis:
      host: redis-11054.c15.us-east-1-4.ec2.redns.redis-cloud.com
      port: 11054
      repositories:
        enabled: false
      username: memo
      password: L1br3123.
  r2dbc:
    url: r2dbc:h2:mem:///exchangedb
    username: sa
    password: 111
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always


api:
  exchange-rate:
      url: https://api.exchangerate.host
      key: 9c099d61b96894fc27fa8faabd356434

cache:
  ttl:
    minutes: 5
server:
  port: 8080

logging:
  level:
    org.springframework.data.redis: DEBUG

